name: Build and Test

on:
  push:

env:
  AWS_REGION: us-east-1
#  AWS_S3_BUCKET: e-commerce-code-deploy-bucket
  AWS_CODE_DEPLOY_APPLICATION: E-Commerce-API
  AWS_CODE_DEPLOY_GROUP: e-commerce-api-group

jobs:
  Build-and-Test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.TEST_SPRING_DATASOURCE_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.TEST_SPRING_DATASOURCE_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build
        run: ./gradlew build -x test

      - name: Test
        run: ./gradlew test
        env:
          TEST_SPRING_DATASOURCE_DRIVER: ${{ secrets.TEST_SPRING_DATASOURCE_DRIVER }}
          TEST_SPRING_DATASOURCE_URL: ${{ secrets.TEST_SPRING_DATASOURCE_URL }}
          TEST_REDIS_HOST: ${{ secrets.TEST_REDIS_HOST }}
          TEST_REDIS_PORT: ${{ secrets.TEST_REDIS_PORT }}
          TEST_SPRING_DATASOURCE_USERNAME: ${{ secrets.TEST_SPRING_DATASOURCE_USERNAME }}
          TEST_SPRING_DATASOURCE_PASSWORD: ${{ secrets.TEST_SPRING_DATASOURCE_PASSWORD }}

      - name: Notify on Slack
        run: |
          if [[ "${{ job.status }}" == 'success' ]]; then
            message="Build and test passed for a commit in branch ${{ github.ref }} by ${{ github.actor }}"
          else
            message="Build or test failed for a commit in branch ${{ github.ref }} by ${{ github.actor }}"
          fi
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"${message}\"}" $SLACK_WEBHOOK_URL
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  Deploy:
    needs: Build-and-Test
    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Api Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/e-commerce -f Dockerfile-api .

      - name: Push Docker Api Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/e-commerce

      - name: Build Docker Admin Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/e-commerce-admin -f Dockerfile-admin .

      - name: Push Docker Admin Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/e-commerce-admin

      - name: Configure AWS credential
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}

#      - name: Upload to S3
#        run: aws deploy push --application-name ${{ env.AWS_CODE_DEPLOY_APPLICATION }} --ignore-hidden-files --s3-location s3://$AWS_S3_BUCKET/cicdtest/$GITHUB_SHA.zip --source .

      - name: Deploy to EC2
        run: aws deploy create-deployment --application-name ${{ env.AWS_CODE_DEPLOY_APPLICATION }} --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name ${{ env.AWS_CODE_DEPLOY_GROUP }} # --s3-location bucket=$AWS_S3_BUCKET,key=cicdtest/$GITHUB_SHA.zip,bundleType=zip

      - name: Notify on Slack
        run: |
          if [[ "${{ job.status }}" == 'success' ]]; then
            message="Deploy step passed for a commit in branch ${{ github.ref }} by ${{ github.actor }}"
          else
            message="Deploy step failed for a commit in branch ${{ github.ref }} by ${{ github.actor }}"
          fi
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"${message}\"}" $SLACK_WEBHOOK_URL
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}